auto:
  create:
    topics:
      enable: 'true'
spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      client-id: topico-pessoa-producer
    properties:
      schema:
        registry:
          url: http://0.0.0.0:8085
      specific:
        avro:
          reader: true

  datasource:
    url: jdbc:h2:mem:mydb;MODE=LEGACY
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  ###
  #   H2 Settings
  ###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true
config:
  retry:
    maxAttempts: 5
    maxDelay: 1000

topico:
  nome: TOPICO_CLIENTE
  client_id: walter_id







